manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: stlimtat
      url-base: https://github.com/stlimtat
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: stlimtat
      revision: main
      import: app/west.yml
    - name: zmk-auto-layer
      remote: urob 
      revision: main
      path: modules/auto-layer
    - name: zmk-helpers
      remote: urob 
      revision: main
      path: modules/helpers
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-tri-state
      remote: urob 
      revision: main
      path: modules/tri-state
  self:
    path: config
